### ISSUE TITLE
Autoconsent standard

### ISSUE THREAD

**Issue by royarisse** [ghostery/autoconsent#39]
Not as much an issue, more a request.

I would like to suggest an autoconsent-standard that can be used by website-developers / cookie-consent developers.

Assume a website has the following code for the cookie-consent's "OK" button:
`<a data-autoconsent="true">OK</a>`

Then this could work as follows:
1. This library looks for elements with a `data-autoconsent` attribute;
2. If the library finds such an element, it fires a click-event;
3. Website-owner implements a (javaScript) listener for the click event and closes the cookie-popup, assuming minimal (functional) cookies.

Perhaps a standard already exists, if so please let me know. I'm looking forward to your opinion :)

**Comment by philipp-classen** [comment]
To the best of my knowledge there is no such standard yet. IMHO, it would be a good idea to have a standardize way that developers can opt-in; there is a shared incentive to avoid site breakage (both from website or cookie-consent developers and from content blockers). It would reduce complexity from the content blocker side (not having to re-engineer detection rules), and it would give more control to the developers of the website or framework to quickly fix some issues without having to wait until a fix lands.

Though I'm in favor, I fear our abilities to push for a standard that will get adoption is limited. Maybe a practical approach would be to start defining such a element in the page and then the auto-consent rules could migrate to that (for the individual site or the consent framework). If more websites or framework would adopt it, it would make sense to implement a detecting in the auto-consent library to automatically detect it (without manually creating a rule).

Would be worth discussing with member of the DuckDuckGo team. They are driving the development of the library and maintaining the rules (https://github.com/duckduckgo/autoconsent/).

cc @sammacbeth

**Comment by royarisse** [comment]
Thanks for your quick response @philipp-classen, really appreciate it!
It's good to know I'm not the only one thinking this is a good idea.
I'll open an issue at DDGs repository to see if I can get more info there.
Thanks again :)
