### ISSUE TITLE
Update auto-consent for TrustArc

### ISSUE THREAD

**Issue by hyebahi** [ghostery/autoconsent#40]
I've included a fix for TA auto-consent on duckduckgo auto-consent repository. Is it possible to pull this request to Ghostery?
https://github.com/duckduckgo/autoconsent/pull/235

Thank you

**Comment by philipp-classen** [comment]
Glad to hear that you got it merged! We are typically following the autoconsent releases from the DuckDuckGo team closely. Thus, your contribution should become part of Ghostery soon.

@chrmod Maybe we should archive this repository and leave a hint that https://github.com/duckduckgo/autoconsent is the source of truth (also for Ghostery)?

**Comment by hyebahi** [comment]
Hi @chrmod 

I hope you are doing well. Would you happen to have any updates? Please let me know if I can help you.

**Comment by philipp-classen** [comment]
> Hi @chrmod
> 
> I hope you are doing well. Would you happen to have any updates? Please let me know if I can help you.

I don't see any release from DuckDuckGo yet. If a new one comes out, we will switch to that version.

**Comment by muodov** [comment]
I've just cut a release for @duckduckgo/autoconsent, feel free to switch :)

**Comment by philipp-classen** [comment]
https://github.com/ghostery/ghostery-extension/pull/1284
