### ISSUE TITLE
Update autoconsent for TrustArc from DuckDuckGo

### ISSUE THREAD

**Issue by hyebahi** [ghostery/autoconsent#42]
Hi @chrmod 
There is an update in the autoconsent from DuckDuckGo that fixes the issue of the modal window closing automatically after a few seconds. Can you review this and update the dependency on Ghostery?
https://github.com/duckduckgo/autoconsent/pull/436

Thank you

**Comment by chrmod** [comment]
Will do. Thank you for letting us know!
